# The Trusty beta Build Environment
sudo: required
dist: trusty

install:
  - sudo apt-get install -y qt5-default qttools5-dev-tools #install necessary Qt files

script:
  - qmake TestPointer.pro #we gonna compile for Unit test first
  - make
  - ./tst_pointertest #run unit test
